
#define C_BOX     _BLUE+CYAN
#define C_TXT     _BLUE+LGREY
#define C_SEL     _BLUE+YELLOW
#define C_NSEL    _BLUE+DGREY
#define C_ASEL    _LGREY+BLUE
#define C_MSEL    _BLUE+WHITE
#define C_MASEL   _LGREY+BLUE
#define C_CHR     _BLUE+DGREY
#define C_TITLE   _BLUE+LCYAN
#define C_SHADOW  _BLACK+DGREY

#define C_WTITLE  _CYAN+BROWN
#define C_WBOX    _CYAN+BLACK
#define C_WTXT    _CYAN+BLACK
#define C_WSEL    _CYAN+WHITE
#define C_WASEL   _RED+YELLOW
#define C_WNSEL   _CYAN+DGREY

#define C_HTITLE  _GREEN+WHITE
#define C_HBOX    _GREEN+WHITE
#define C_HTXT    _GREEN+BLACK

